version: "3.8"

services:
  backend:
    build:
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    depends_on:
      - redis
    environment:
      - RAGFLOW_API_KEY=ragflow-ViN2QxODljZDI3MjExZWY5MTk3MDI0Mm
      - RAGFLOW_BASE_URL=http://hcux402.teagasc.net:9380
      - AGENT_NAME=ACRES
      - REDIS_URL=redis://redis:6379
    networks:
      - reflex_chat_network
    volumes:
       - /opt/ACRES-AI-RAG/certs/hcux402.teagasc.net.pem:/etc/nginx/hcux402.teagasc.net.pem
       - /opt/ACRES-AI-RAG/certs/hcux402.teagasc.net.key:/etc/nginx/hcux402.teagasc.net.key

  frontend:
    build:
      dockerfile: web.Dockerfile
    ports:
      - 3000:80
    depends_on:
      - backend
    networks:
      - reflex_chat_network

  redis:
    image: redis
    networks:
        - reflex_chat_network

networks:
  reflex_chat_network:
    driver: bridge 
